AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bundle/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "app/controllers/blazer/*"
    - "app/controllers/external/api/v1/swagger/swagger_responses/*"
    - "app/controllers/external/api/v1/swagger/responses.rb"
    - "spec/models/regression/*"
    # System folders
    - "etc/**/*"
    - "sys/**/*"
    - "var/**/*"
    - "tmp/**/*"
    - "sbin/**/*"
    - "usr/**/*"
    - "run/**/*"
    - "lib/**/*"
    - "usr/**/*"
    - "proc/**/*"

# Keep these options sorted :)

AccessModifierIndentation:
  Enabled: false

AlignHash:
  EnforcedColonStyle: key

AlignParameters:
  Enabled: false

AndOr:
  Enabled: false

Documentation:
  Enabled: false

GuardClause:
  Enabled: false

LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 5

Metrics/AbcSize:
  Max: 20

ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

NumericLiterals:
  MinDigits: 7

SignalException:
  Enabled: false

SpaceBeforeBlockBraces:
  Enabled: false

SpaceInsideBlockBraces:
  EnforcedStyle: space

StringLiterals:
  Enabled: false

WordArray:
  Enabled: false

ActionFilter:
  Enabled: false
BlockLength:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
AmbiguousBlockAssociation:
  Enabled: false
# These two should be removed in the future when Rubocop fixes issues with them
Style/SafeNavigation:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
